[workspace]
resolver="2"
members = [
    "gb-core",           # Core domain models and traits
    "gb-api",            # API layer and server implementation
    "gb-media",          # Media processing and WebRTC handling

    "gb-messaging",      # Message queue and real-time communication
    "gb-storage",        # Database and storage implementations
    "gb-monitoring",     # Metrics, logging and monitoring
    "gb-auth",           # Authentication and authorization
    "gb-testing",        # Integration and load testing
    "gb-migrations",     # Database migrations
    #"gb-cloud",          # Cloud provider integrations
    #"gb-vm",            # Virtual machine and BASIC compiler
    "gb-automation",     # Web and process automation
    "gb-image",         # Image processing capabilities
]

# [workspace.lints.rust]
# unused_imports = "allow"
# dead_code = "allow"
# unused_variables = "allow"
# dependency_on_unit_never_type_fallback = "allow"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["GeneralBots Team"]
license = "MIT"

[workspace.dependencies]
# Core async runtime and utilities
tokio = { version = "1.34", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
parking_lot = "0.12"

# Web framework and servers
axum = { version = "0.7.9", features = ["ws", "multipart"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "fs"] }
hyper = { version = "1.1", features = ["full"] }
tonic = { version = "0.10", features = ["tls", "transport"] }

# Database and storage
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "mysql", "sqlite", "uuid", "time", "json"] }
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }
tikv-client = "0.3"
sea-orm = { version = "0.12", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"] }

# Message queues
rdkafka = { version = "0.36", features = ["cmake-build", "ssl"] }
lapin = "2.3"

# Serialization and data formats
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
protobuf = "3.3"
prost = "0.12"
csv = "1.3"

# WebRTC and media processing
webrtc = "0.9"
gstreamer = "0.21"
opus = "0.3"
image = "0.24"

# Authentication and security
jsonwebtoken = "9.2"
argon2 = "0.5"
ring = "0.17"
reqwest = { version = "0.11", features = ["json", "stream"] }

# Cloud services
aws-sdk-core = "1.1"
azure_core = "0.15"
azure_identity = "0.15"
google-cloud-storage = "0.16"

# Monitoring and metrics
prometheus = "0.13.0"
opentelemetry = { version = "0.20", features = ["rt-tokio"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Testing
criterion = "0.5"
mockall = "0.12"
fake = { version = "2.9", features = ["derive"] }
rstest = "0.18"

# Utilities
uuid = { version = "1.6", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
anyhow = "1.0"
regex = "1.10"
url = "2.5"
rand = "0.8"
base64 = "0.21"
semver = "1.0"
walkdir = "2.4"
tempfile = "3.9"

# Web assembly
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["WebSocket", "WebRtcPeerConnection"] }

# Natural language processing 
rust-bert = "0.21"
tokenizers = "0.15"
whatlang = "0.16"

# PDF and document processing
pdf = "0.8"
docx = "1.1"
zip = "0.6"

[workspace.metadata]
msrv = "1.70.0"
