[workspace]
resolver = "2"
members = [
    "gb-core",
    "gb-server",
    "gb-media",
    "gb-messaging",
    "gb-storage",
    "gb-monitoring",
    "gb-auth",
    "gb-testing",
    "gb-migrations",
    "gb-cloud",
    "gb-vm",
    "gb-automation",
    "gb-image",
    "gb-utils",
    "gb-document",
    "gb-file",
    "gb-llm",
    "gb-calendar",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["General Bots Maintainers"]
license = "MIT"

[workspace.dependencies]
# Core async runtime and utilities
tokio = { version = "1.34", features = ["full"] }
tokio-tungstenite = { version = "0.24.0", features = ["native-tls"] }
tungstenite = "0.20"
tokio-test = "0.4"
tokio-stream = "0.1.17"
async-trait = "0.1"
futures = "0.3"
futures-util = "0.3"  # Add futures-util here
parking_lot = "0.12"

# Web framework and servers
axum = { version = "0.7.9", features = ["ws", "multipart"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "fs"] }
hyper = { version = "1.1", features = ["full"] }
hyper-util = { version = "0.1" }
tonic = { version = "0.10", features = ["tls", "transport"] }
actix-multipart = "0.4"


# Database and storage
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "mysql", "sqlite", "uuid", "time", "json"] }
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }
tikv-client = "0.3"
sea-orm = { version = "0.12", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"] }

# Message queues
rdkafka = { version = "0.36", features = ["cmake-build", "ssl"] }
lapin = "2.3"


# Drive, Serialization and data formats
minio = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
protobuf = "3.3"
prost = "0.12"
csv = "1.3"

# WebRTC and media processing
webrtc = "0.9"
gstreamer = "0.21"
opus = "0.3"
image = "0.24"

# Authentication and security
zitadel = {version = "5.5.1", features = ["api-common", "api-auth-v1", "zitadel-auth-v1", "credentials", "interceptors"]}
jsonwebtoken = "9.2"

argon2 = "0.5"
ring = "0.17"
reqwest = { version = "0.11", features = ["json", "stream"] }

# Cloud services
aws-sdk-core = "1.1"
azure_core = "0.15"
azure_identity = "0.15"
google-cloud-storage = "0.16"

# Monitoring and metrics
prometheus = "0.13.0"
opentelemetry = { version = "0.20", features = ["rt-tokio"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Testing
criterion = "0.5"
mockall = "0.12"
fake = { version = "2.9", features = ["derive"] }
rstest = "0.18"

# Utilities
actix-web = "4.0.1"  
uuid = { version = "1.6", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
anyhow = "1.0"
regex = "1.10"
url = "2.5"
rand = "0.8"
base64 = "0.21"
semver = "1.0"
walkdir = "2.4"
tempfile = "3.9"
dotenv = "0.15"
lettre = "0.10"
sanitize-filename = "0.3"

# Web assembly
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["WebSocket", "WebRtcPeerConnection"] }

# Natural language processing
rust-bert = "0.21"
tokenizers = "0.15"
whatlang = "0.16"

# PDF and document processing
pdf = "0.8"
docx = "1.1"
zip = "0.6"

[workspace.metadata]
msrv = "1.70.0"