[package]
name = "gbserver"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "File server with MinIO integration"
license = "MIT"
repository = ""

[dependencies]
actix-web = "4"
actix-multipart = "0.6"
tokio = { version = "1", features = ["full"] }
log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
dotenv = "0.15"
tempfile = "3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
minio = { git = "https://github.com/minio/minio-rs", branch = "master" }
tokio-stream = "0.1.17"
jmap-client = "0.3.2"
