name: GBCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: gbo
    
    steps:
    - name: Disable SSL verification (temporary)
      run: git config --global http.sslVerify false

    - uses: actions/checkout@v4

    - name: Run build
      run: |
        export PATH=\"\$HOME/.cargo/bin:\$PATH\"
        cargo build --workspace --release --locked

    - name: Deploy binary
      run: |
        sudo cp ./target/release/gbserver /opt/gbo/bin/system
        sudo chmod +x /opt/gbo/bin/system/gbserver
        
        sudo systemctl restart gbserver
        