name: GBCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: gbo

    steps:
      - name: Disable SSL verification (temporary)
        run: git config --global http.sslVerify false

      - uses: actions/checkout@v4

      - name: Install Rust
        uses: msrd0/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run build
        run: |
          sudo cp  /opt/gbo/bin/system/.env .
          cargo build --locked

      - name: Deploy binary and restart
        run: |
          lxc exec bot:pragmatismo-system -- systemctl stop system

          sudo cp ./target/debug/gbserver /opt/gbo/bin/system
          sudo chmod +x /opt/gbo/bin/system/gbserver

          lxc exec bot:pragmatismo-system -- systemctl start system
