load_test:
  users: 100
  duration: 300  # seconds
  ramp_up: 60    # seconds
  scenarios:
    - auth
    - api
    - webrtc

performance_test:
  iterations: 1000

performance_test:
  iterations: 1000
  warmup_iterations: 100
  sample_size: 100
  threads: 8
  scenarios:
    - api_latency
    - database_queries
    - media_processing

stress_test:
  duration: 1800  # 30 minutes
  concurrent_users: 1000
  scenarios:
    - continuous_requests
    - websocket_connections
    - file_uploads

chaos_test:
  duration: 3600  # 1 hour
  interval: 300   # 5 minutes between actions
  actions:
    - kill_random_pod
    - network_partition
    - resource_exhaustion
    - disk_pressure

metrics:
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: true
    port: 3000
  jaeger:
    enabled: true
    port: 16686

reports:
  formats:
    - json
    - html
    - pdf
  output_dir: "./test-reports"
  retain_days: 30
