apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-processor
  namespace: general-bots
spec:
  replicas: 3
  selector:
    matchLabels:
      app: document-processor
  template:
    metadata:
      labels:
        app: document-processor
    spec:
      containers:
      - name: document-processor
        image: generalbotsproject/document-processor:latest
        ports:
        - containerPort: 8080
        env:
        - name: RUST_LOG
          value: info
        volumeMounts:
        - name: temp
          mountPath: /tmp
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: temp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: document-processor
  namespace: general-bots
spec:
  selector:
    app: document-processor
  ports:
  - port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: document-processor-config
  namespace: general-bots
data:
  processing.conf: |
    max_file_size = 50MB
    supported_formats = [
      "pdf",
      "docx",
      "xlsx"
    ]
    temp_dir = "/tmp"
    processing_timeout = 300s
